# Подтягиваем тексты песен из имеющегося датасета

In [2]:
from kpop_datasets.utils import data_parser

your_dict = data_parser.get_dict(2022)

In [6]:
your_dataframe = data_parser.get_df(2010, 2023)

[data_parser] Parsed data to DataFrame: 2010 >> 2026....

In [12]:
your_dataframe.head()

,year,month,rank,song_id,song_name,album,released_year,released_month,released_day,artist,genre,lyric_writer,composer,arranger,lyrics_row,lyrics
0,2010,1,1,2511561,우리 사랑하게 됐어요.,우리 사랑하게 됐어요,2009.0,12.0,17.0,가인,댄스,김이나,조권,가인,49,"[맨 처음 그 날의 난, 아마 몰랐겠지 이런 날, 어색했었던 우리 모습이, 어제만 ..."
1,2010,1,2,2366796,너 때문에,너 때문에,2009.0,11.0,25.0,애프터스쿨,댄스,용감한 형제,용감한 형제,용감한 형제,99,"[아직도 나 그대를 잊지 못해, I never forget boy, I never ..."
2,2010,1,3,2371262,Bo Peep Bo Peep,Absolute First Album,2009.0,11.0,27.0,티아라,댄스,신사동 호랭이,최규성,신사동 호랭이,77,"[Bo Peep Bo Peep Bo Peep, Bo Peep Bo Peep Bo P..."
3,2010,1,4,2425271,오늘 헤어졌어요,3rd Album Part.B 'Growing Season',2009.0,12.0,11.0,윤하 (YOUNHA),발라드,박화요비,이관,이관,36,"[새하얀 머플러에 얼굴을 묻고, 붉어진 눈을 깜빡이며 널 기다렸어, 무슨 얘길 하고..."
4,2010,1,5,2371261,처음처럼,Absolute First Album,2009.0,11.0,27.0,티아라,댄스,Hitman Bang,Hitman Bang,WONDERKID,71,"[왜 자꾸 두근두근 대죠, 이 내 가슴이, 자꾸만, 왜터질거같죠, 자꾸만, 왜 자꾸..."

## Отбираем только тех исполнителей, которые есть у нас в базе

In [8]:
import pandas as pd

In [10]:
df = pd.read_csv("merged_clean.csv")

/var/folders/pj/1f7_67jj6570ccyh9p9qh9lr0000gn/T/ipykernel_63782/195734925.py:1: DtypeWarning: Columns (0: track_id, 1: artist_name, 2: track_name, 3: album_name, 4: album_release_date, 5: group type, 6: availability, 7: id, 8: genres, 9: name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("merged_clean.csv")

In [14]:
df_lyrics = df.merge(
    your_dataframe[['song_name', 'lyrics']],
    left_on='track_name',
    right_on='song_name',
    how='left'
)

In [17]:
df_lyrics.head()

,Unnamed: 0,track_id,artist_name,track_name,album_name,album_release_date,duration_ms,explicit,track_number,disc_number,...,availability,sales,first places,id,followers,genres,name,popularity,song_name,lyrics
11,11.0,6O1CSm7NJchlrdZgTIC5hg,&TEAM,Maybe,Samidare,2024-05-08,190433.0,0.0,3.0,1.0,...,All data available,1271052.0,0.0,NaN,NaN,NaN,NaN,NaN,Maybe,"[차가운 가슴이 어느새 조금씩, 녹아 내렸나 봐 니가 들어왔어, 그리고 나도 몰래 ..."
12,11.0,6O1CSm7NJchlrdZgTIC5hg,&TEAM,Maybe,Samidare,2024-05-08,190433.0,0.0,3.0,1.0,...,All data available,1271052.0,0.0,NaN,NaN,NaN,NaN,NaN,Maybe,"[차가운 가슴이 어느새 조금씩, 녹아 내렸나 봐 니가 들어왔어, 그리고 나도 몰래 ..."
13,11.0,6O1CSm7NJchlrdZgTIC5hg,&TEAM,Maybe,Samidare,2024-05-08,190433.0,0.0,3.0,1.0,...,All data available,1271052.0,0.0,NaN,NaN,NaN,NaN,NaN,Maybe,"[차가운 가슴이 어느새 조금씩, 녹아 내렸나 봐 니가 들어왔어, 그리고 나도 몰래 ..."
57,55.0,5tXHIJEn2mDsoxtS5QvegB,(G)I-DLE,LATATA,I am,2018-05-02,202772.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LATATA,"[기나긴 너와 이 밤을, 너와 이렇게 너와, 기다린 너와 시간을, 너와 이렇게 너와..."
58,55.0,5tXHIJEn2mDsoxtS5QvegB,(G)I-DLE,LATATA,I am,2018-05-02,202772.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LATATA,"[기나긴 너와 이 밤을, 너와 이렇게 너와, 기다린 너와 시간을, 너와 이렇게 너와..."

In [16]:
df_lyrics = df_lyrics.dropna(subset=['lyrics'])

In [18]:
len(df_lyrics)

7763

In [20]:
df_lyrics.to_csv("lyrics_first_try.csv", index=False)
df_lyrics.to_excel("lyrics_first_try.xlsx", index=False)

# Смотрим, для скольких песен спарсились тексты

In [2]:
import pandas as pd

In [76]:
# загружаем датасетик из genius и наш основной
df_base = pd.read_csv("df_to_parse.csv", low_memory=False)
df_genius = pd.read_csv("lyrics/second_try_3000.csv", low_memory=False)

In [ ]:
# песни, для которых lyrics не пустой
lyrics_df = df_genius[df_genius["lyrics"].notna() & (df_genius["lyrics"].astype(str).str.strip() != "")]

In [126]:
print(len(df_genius) - len(lyrics_df))

3978

In [138]:
len(lyrics_df)

9825

In [112]:
lyrics_df.head()

,Unnamed: 0,track_id,artist_name,track_name,album_name,album_release_date,duration_ms,explicit,track_number,disc_number,...,loudness,speechiness,acousticness,instrumentalness,liveness,valence,energy_danceability_score,gender_type,is_group,lyrics
2,3,2BQEQhfUtEJXtbxaOv96Xg,&TEAM,Koegawari,Koegawari,2024-07-18,198486,0,1,1,...,-4.057,0.0582,0.0160,0.000003,0.2310,0.798,0.674016,0.0,1.0,Don't think I can't feel anymore\nFeel anymore...
37,41,39InAkwgmsMyWUAC0axsTU,&TEAM,Comment from &TEAM 4,Weverse Con Festival 2025,2025-06-24,99383,0,4,1,...,-10.640,0.3570,0.8730,0.000016,0.8010,0.102,0.310877,0.0,1.0,Overview | How does annotating books help to d...
38,47,1z4Ruz3ecnINTOQJpi8qMk,&TEAM,君にカエル (Maybe),君にカエル (Maybe),2024-04-28,190453,0,1,1,...,-5.397,0.0356,0.1720,0.000000,0.1740,0.309,0.432216,0.0,1.0,「雨が降りそう」\n君のストーリー (Maybe)\n灰色の空 僕と似てる\n言葉に頼りたく...
39,50,6KuDZz7xhIRt620BpkK0Tg,(G)I-DLE,HANN (Alone) (i-dle ver.),We are i-dle,2025-05-02,205826,0,2,1,...,-4.023,0.0326,0.0778,0.000000,0.2000,0.208,0.471888,1.0,1.0,"Do you remember, you remember, remember what y..."
41,53,4nb4COXS4wzxgcBDl7b6O7,(G)I-DLE,HWAA (i-dle ver.),We are i-dle,2025-05-02,197320,0,9,1,...,-3.922,0.0482,0.0165,0.000000,0.0913,0.212,0.494648,1.0,1.0,"Yeah\n\n차디찬 한겨울이 덮친 듯, yeah\n시간은 다 얼어버리고\n잔인한 ..."

In [80]:
len(df_base["track_id"])

34504

In [88]:
tracks_with_lyrics = lyrics_df["track_id"].nunique()
total_tracks = df_base["track_id"].nunique()

print(f"Песен с текстом: {tracks_with_lyrics}")
print(f"Всего песен: {total_tracks}")
print(f"Покрытие: {tracks_with_lyrics / total_tracks:.2%}")

Песен с текстом: 1952
Всего песен: 34504
Покрытие: 5.66%

In [82]:
# удаляем дубли
lyrics_df_2 = lyrics_df.drop_duplicates(subset=["track_id"])

In [27]:
# удаляем дубли в основной базе
df_base = df_base.drop_duplicates(subset=["track_id"])

In [31]:
df_base.to_csv('df_base_wo_duplicates.csv', index=False)
lyrics_df.to_csv('df_lyrics_p1_wo_duplicates.csv', index=False)

# Предобрабатываем данные — достаем все метаданные, которые можем

In [33]:
from ast import literal_eval

In [32]:
sorted(df_base["group type"].dropna().unique())

['coed group', 'female group', 'female soloist', 'male group', 'male soloist']

In [37]:
all_values = set()

for value in df_base["genres"].dropna():
    try:
        parsed = literal_eval(str(value))

        if isinstance(parsed, list):
            all_values.update(parsed)
        else:
            all_values.add(str(parsed))

    except Exception:
        all_values.add(str(value))

print(f"Уникальных значений: {len(all_values)}")

for v in sorted(all_values):
    print(v)

Уникальных значений: 55
anime
asian american hip hop
battle rap
bedroom r&b
chill r&b
chillhop
chinese electropop
chinese idol pop
classic k-pop
classic korean pop
classical piano
dance pop
deep latin alternative
diva house
freestyle
hong kong hip hop
j-division
j-idol
j-metal
j-pop
j-pop boy group
j-rock
japanese chillhop
japanese emo
joseon pop
k-indie
k-pop
k-pop ballad
k-pop boy group
k-pop girl group
k-rap
k-rock
korean city pop
korean classical performance
korean classical piano
korean dream pop
korean drill
korean electronic
korean electropop
korean indie folk
korean indie rock
korean metal
korean old school hip hop
korean ost
korean pop
korean r&b
korean singer-songwriter
korean superband
korean trap
korean underground rap
lo-fi beats
pop
shibuya-kei
visual kei
world worship

In [50]:
def parse_artist_type(row):
    group_type = str(row["group type"]).strip().lower()

    try:
        genres = literal_eval(str(row["genres"]))
        if not isinstance(genres, list):
            genres = []
        genres = [g.lower() for g in genres]
    except:
        genres = []

    gender_type = None
    is_group = None

    # Пол

    if group_type in ["female group", "female soloist"]:
        gender_type = 1

    elif group_type in ["male group", "male soloist"]:
        gender_type = 0

    elif group_type == "coed group":
        gender_type = 3

    else:
        if "k-pop girl group" in genres:
            gender_type = 1

        elif (
            "k-pop boy group" in genres
            or "j-pop boy group" in genres
        ):
            gender_type = 0

    # Соло/группа

    if group_type in ["female soloist", "male soloist"]:
        is_group = 0

    elif group_type in [
        "female group",
        "male group",
        "coed group"
    ]:
        is_group = 1

    elif (
        "k-pop girl group" in genres
        or "k-pop boy group" in genres
        or "j-pop boy group" in genres
    ):
        is_group = 1

    return pd.Series([gender_type, is_group])

In [51]:
df_base[["gender_type", "is_group"]] = df_base.apply(parse_artist_type, axis=1)

In [52]:
print(df_base["gender_type"].value_counts(dropna=False))
print(df_base["is_group"].value_counts(dropna=False))

gender_type
NaN    19853
0.0    15057
1.0     7351
3.0      137
Name: count, dtype: int64
is_group
NaN    19853
1.0    13460
0.0     9085
Name: count, dtype: int64

In [61]:
print(df_base.head())

   Unnamed: 0                track_id artist_name  \
0           0  1lbn4BraBUHY7jFf3oe1WY       &TEAM
1           1  6EGXuyLBotCYrtvOtDOWrM       &TEAM
2           2  0TvIjzfQogOEL43VKZ9nuz       &TEAM
3           3  2BQEQhfUtEJXtbxaOv96Xg       &TEAM
4           4  1zTLMgEeNgwAeUidaBHo4q       &TEAM

                           track_name                    album_name  \
0  Running with the pack - &TEAM ver.           First Howling : NOW
1                           Yukiakari                     Yukiakari
2              Dropkick - Korean ver.              雪明かり (Yukiakari)
3                           Koegawari                     Koegawari
4                     Wonderful World  Magic Hour / Wonderful World

  album_release_date  duration_ms  explicit  track_number  disc_number  ...  \
0         2023-11-15       185640         0            18            1  ...
1         2024-12-16       193704         0             1            1  ...
2         2024-12-17       178765         0            22            1  ...
3         2024-07-18       198486         0             1            1  ...
4         2025-01-08       150057         0             2            1  ...

   energy_danceability_score  group type        availability      sales  \
0                   0.506522  male group  All data available  1271052.0
1                   0.382776  male group  All data available  1271052.0
2                   0.575757  male group  All data available  1271052.0
3                   0.674016  male group  All data available  1271052.0
4                   0.754202  male group  All data available  1271052.0

   first places  followers  genres  popularity  gender_type  is_group
0           0.0        NaN     NaN         NaN          0.0       1.0
1           0.0        NaN     NaN         NaN          0.0       1.0
2           0.0        NaN     NaN         NaN          0.0       1.0
3           0.0        NaN     NaN         NaN          0.0       1.0
4           0.0        NaN     NaN         NaN          0.0       1.0

[5 rows x 37 columns]

In [55]:
df_base.to_excel('df_base_all_meta.xlsx', index=False)
df_base.to_csv('df_base_all_meta.csv', index=False)

# Формируем данные для обучения

Смотрим пустые значения

In [54]:
missing_counts = df_base.isna().sum()
print(missing_counts)

Unnamed: 0                        0
track_id                          0
artist_name                       0
track_name                        2
album_name                       11
album_release_date                0
duration_ms                       0
explicit                          0
track_number                      0
disc_number                       0
track_popularity                  0
album_popularity                  0
track_vs_album_popularity         0
artist_popularity                 0
artist_followers                  0
album_vs_artist_popularity        0
tempo                             0
key                               0
mode                              0
danceability                      0
energy                            0
loudness                          0
speechiness                       0
acousticness                      0
instrumentalness                  0
liveness                          0
valence                           0
energy_danceability_score         0
group type                    22522
availability                  22522
sales                         22522
first places                  22522
followers                      7545
genres                         7545
popularity                     7545
gender_type                   19853
is_group                      19853
dtype: int64

In [56]:
# удаляем те столбцы, в которых слишком много пропусков — сохраним максимум информации

df_meta_ml = df_base.drop(columns=['group type', 'genres', 'availability', 'sales', 'first places', 'followers', 'popularity', 'gender_type', 'is_group'])

In [59]:
df_meta_ml = df_meta_ml.dropna()
print(len(df_meta_ml))

42386

In [60]:
df_meta_ml.to_csv('df_meta_ml.csv', index=False)
df_meta_ml.to_excel('df_meta_ml.xlsx', index=False)

In [62]:
# теперь сохраняем те столбцы, в которых есть информация о поле/группе

df_sex = df_base.dropna(subset=['gender_type', 'is_group'])

In [65]:
missing_counts = df_sex.isna().sum()
print(missing_counts)

Unnamed: 0                    0
track_id                      0
artist_name                   0
track_name                    1
album_name                    0
album_release_date            0
duration_ms                   0
explicit                      0
track_number                  0
disc_number                   0
track_popularity              0
album_popularity              0
track_vs_album_popularity     0
artist_popularity             0
artist_followers              0
album_vs_artist_popularity    0
tempo                         0
key                           0
mode                          0
danceability                  0
energy                        0
loudness                      0
speechiness                   0
acousticness                  0
instrumentalness              0
liveness                      0
valence                       0
energy_danceability_score     0
gender_type                   0
is_group                      0
dtype: int64

In [64]:
#дочищаем те столбцы, где много пустой информации — сохраним максимум

df_sex = df_sex.drop(columns=['group type', 'genres', 'availability', 'sales', 'first places', 'followers', 'popularity'])

In [66]:
df_sex = df_sex.dropna()
print(len(df_sex))

22544

In [67]:
df_sex.to_excel('df_sex.xlsx', index=False)
df_sex.to_csv('df_sex.csv', index=False)

## Подтянем тексты для обеих получившихся табличек

In [70]:
lyrics_map = lyrics_df.set_index("track_id")["lyrics"]

df_sex["lyrics"] = df_sex["track_id"].map(lyrics_map)
df_meta_ml["lyrics"] = df_meta_ml["track_id"].map(lyrics_map)

In [72]:
missing_counts = df_meta_ml.isna().sum()
print(missing_counts)

Unnamed: 0                        0
track_id                          0
artist_name                       0
track_name                        0
album_name                        0
album_release_date                0
duration_ms                       0
explicit                          0
track_number                      0
disc_number                       0
track_popularity                  0
album_popularity                  0
track_vs_album_popularity         0
artist_popularity                 0
artist_followers                  0
album_vs_artist_popularity        0
tempo                             0
key                               0
mode                              0
danceability                      0
energy                            0
loudness                          0
speechiness                       0
acousticness                      0
instrumentalness                  0
liveness                          0
valence                           0
energy_danceability_score         0
lyrics                        34492
dtype: int64

In [74]:
df_sex_lyrics = df_sex.copy()
df_meta_ml_lyrics = df_meta_ml.copy()

df_sex_lyrics = df_sex_lyrics.dropna()
df_meta_ml_lyrics = df_meta_ml_lyrics.dropna()

df_sex_lyrics.to_csv('df_sex_lyrics.csv', index=False)
df_meta_ml_lyrics.to_csv('df_meta_ml_lyrics.csv', index=False)

In [91]:
print(len(df_sex_lyrics))
print(len(df_meta_ml_lyrics))

6465
7894